name: Trigger Event | Action Plan
description: Issue template for addressing triggering events and creating action plans

title: '[TRIGGER] '
labels: incident

body:
  - type: checkboxes
    id: actions
    attributes:
      label: Checklist for Trigger Event | Action Plan
      description: Select the appropriate actions to address the triggering event
      options:
        - Identify and acknowledge the nature, severity, and impact of the event
        - Inform all team leads about the event
        - Schedule an emergency meeting with team leads
        - Evaluate impact on ongoing projects, timelines, resources, and deliverables
        - Determine priority levels for affected projects
        - Assess resource reallocation or priority adjustments
      required: true

  - type: input
    id: issue_time
    attributes:
      label: Issue Occurrence Time
      description: Enter the time when the issue occurred
      required: true

  - type: input
    id: issue_discoverer
    attributes:
      label: Issue Discoverer
      description: Provide the name of the person who discovered the issue
      required: true
